name: "SSD"
services:
  backend:
      build:
        dockerfile: Dockerfile.backend
        context: .
      ports:
        - "8000:8000"
      depends_on:
        - db
        - redis

  redis:
      image: "redis:latest"
      ports:
        - "6379:6379"